### ISSUE TITLE
'Rating' Attributes not showing correctly on responses 

### ISSUE THREAD

**Issue by atorrance** [ShepherdDev/rock-survey-system#11]
An attribute with a field type of Rating does not show correctly on survey responses or charts, they instead show as html: <i class='fa fa-rating-selected'></i><i class='fa fa-rating-selected'></i><i class='fa fa-rating-selected'></i><i class='fa fa-rating-selected'></i><i class='fa fa-rating-selected'></i>

**Comment by cabal95** [comment]
Hi @atorrance! Unfortunately I think that is an issue with the rating field type itself. When requesting the "condensed" version it still returns HTML to make the pretty. Unfortunately since what it is displaying is font awesome icons I can't even just strip the HTML because then you would be left with a blank string. If I recall, it has the same issue when exporting to Excel if you use that field type.

**Comment by raufrecht** [comment]
The database stores the rating as an integer and RawValue returns that integer.

**Comment by cabal95** [comment]
In order to fix a different bug that had to do with the rating field breaking the filters this has been fixed. Special logic has been added to deal with the Rating field specifically on the charts page. There are probably other field types that will still exhibit this behavior on the charts page though. This fix will be in version 2.6.0 of the plugin.
