### ISSUE TITLE
Feature Request: Save a person Id without being logged in.

### ISSUE THREAD

**Issue by robertnock** [ShepherdDev/rock-survey-system#12]
Hi,

I have a number of people without system Login's.  I'd like to be able to email these people with a unique link to a survey.  That unique link would have their ID embedded.  Would it be possible to then have the survey code use that ID to allocate the results to that person?

**Comment by robertnock** [comment]
Also, how do you enter test mode?

**Comment by cabal95** [comment]
Hi @robertnock.

If you are asking about sending to people that do not exist in Rock at all, then no that isn't possible.

If you are asking about sending to people who have a Person record in Rock, but just don't have a login yet, then Yes. Though that has nothing to do with the Survey plugin. Rock has the ability to generate those links for you so that when the user clicks the link they are automatically logged in even if they don't have a username/password setup yet.

The Lava documentation talks about it's use here: https://community.rockrms.com/lava/filters/person-filters#persontokencreate

You can also ask in Rocket Chat for some guidance on exactly how to make that work. But basically, you need to make sure external users can get to the survey page (probably by creating one on your public site), build a DataView or Group of all the people who will take the survey and then send a new communication to that group with the URL and token.

Make sure you test it on a small group of yourself and one other person before sending it to everybody. If you do it wrong, you can unintentionally send out a link that logs everybody in with your own account.

**Comment by robertnock** [comment]
Hi,

Great.  I hadn’t twigged that.  And I went and wrote a whole lot of Javascript for nothing ☺

Thanks,
Rob

From: Daniel Hazelbaker ***@***.***>
Date: Saturday, 24 July 2021 at 19:05
To: ShepherdDev/rock-survey-system ***@***.***>
Cc: Robert Nock ***@***.***>, Mention ***@***.***>
Subject: Re: [ShepherdDev/rock-survey-system] Feature Request: Save a person Id without being logged in. (#12)

Hi @robertnock<https://github.com/robertnock>.

If you are asking about sending to people that do not exist in Rock at all, then no that isn't possible.

If you are asking about sending to people who have a Person record in Rock, but just don't have a login yet, then Yes. Though that has nothing to do with the Survey plugin. Rock has the ability to generate those links for you so that when the user clicks the link they are automatically logged in even if they don't have a username/password setup yet.

The Lava documentation talks about it's use here: https://community.rockrms.com/lava/filters/person-filters#persontokencreate

You can also ask in Rocket Chat for some guidance on exactly how to make that work. But basically, you need to make sure external users can get to the survey page (probably by creating one on your public site), build a DataView or Group of all the people who will take the survey and then send a new communication to that group with the URL and token.

Make sure you test it on a small group of yourself and one other person before sending it to everybody. If you do it wrong, you can unintentionally send out a link that logs everybody in with your own account.
