### ISSUE TITLE
Multi-select Presenting Lava, Not Results

### ISSUE THREAD

**Issue by debbiethurston** [ShepherdDev/rock-survey-system#4]
We are on Rock V9.3 and using the latest survey plugin.  For one of our fields (which is multi-select), when you enter the actual results instance, it is showing HTML instead of the actual result. You can see the actual text in the grid, but not when you open the actual instance.

**Comment by cabal95** [comment]
Hi Debbie,

Thanks for the report. Can you post a screenshot of the Survey Question (attribute) configuration as well as a screenshot of the result instance screen?  I don't have a 9.3 instance handy but I'll see if I can replicate on the demo site or something in case it doesn't show up in our  9.1 instance (we are a bit behind).

**Comment by debbiethurston** [comment]
Here are three images.  Let me know if you need more.  Thanks so much.

**Comment by cabal95** [comment]
@debbiethurston Hm. They didn't come through, you might need to login to github and post them directly instead of via e-mail.

**Comment by debbiethurston** [comment]
![Mid-point_Error](https://user-images.githubusercontent.com/31704449/69076566-c08e0780-0a01-11ea-9c9d-17c9a19997f6.jpg)

**Comment by debbiethurston** [comment]
![Mid-point_Results](https://user-images.githubusercontent.com/31704449/69077181-0e573f80-0a03-11ea-9ee8-22e824cf2988.jpg)

**Comment by debbiethurston** [comment]
![Mid-point_Resutls_Error](https://user-images.githubusercontent.com/31704449/69077208-1b742e80-0a03-11ea-9be4-454ba29c3c46.jpg)

**Comment by cabal95** [comment]
Got it! thanks for the images. Didn't even know that `Check List` field type existed. I took a look at the code and it seems to be an issue with that field itself. When not "display condensed" it renders out HTML instead of plain text. The only way to change that in the survey plugin would be to display all the responses in "condensed" format, which would, among other things, limit them to 100 characters.

So in order to fix this, it would really need to be fixed in core. Though I don't know if that change would have any unintended consequences. :/
