### ISSUE TITLE
Reporting Suggestion

### ISSUE THREAD

**Issue by rutledgek** [ShepherdDev/rock-survey-system#5]
I think what you have here is great for throwing together a quick survey, however, I was wondering if you would consider exploring the reporting side.  Here is what I am thinking, but I don't know if it can be done.

For each question allow a few extra fields for reporting:
1. Cumulative(adds all responses together), Count(Counts the number of times each response was given), Average(average all responses), List(list all responses)
2. Depending on answers above or just a common list: Graph Types that work with that answer(i.e. bar, line, pie, donut, etc).
3. A reporting block that takes a survey id and then looks at each field's scoring choice and graph option and displays a summary of the survey based on each question's reporting selections.

**Comment by cabal95** [comment]
A custom reporting block would be possible, but would take a bit of work to iron out how to let you build the report quickly. i.e. if you have a 25 question survey some of which are multiple choice, number fields, plain text input, etc. If you have to go through and select which fields to show and how to show them (bar vs pie for example) it would be a pretty time consuming task. If they had to do that each time they wanted to view the chart it wouldn't get a lot of use.

There are some ways to make it easier, such as a new entity that lets you build "visual reports" for the surveys so you can pick which report you want to view. But that's a pretty heafty undertaking.

Reporting is something I'd like to expand at some point, but how to do that in a way that doesn't cost us a ridiculous amount of work for something we don't get anything back from (all proceeds go directly to Spark) is something to figure out. As you can imagine, everybody will want things displayed differently, some as pie charts, some as bar charts. As you mentioned, sometimes you just want a chart of how many times a question was answered vs left blank, etc.

I would like to expand this as well to take advantage of some new features in Rock that should make it easier to customize the surveys with pre/post HTML, multiple pages of questions and possibly conditional questions and at that time we'll review the possibility of also expanding reporting quite a bit too. In the mean time I'll leave this open as a place to gather reporting ideas.

**Comment by cabal95** [comment]
Hey Kevin, so as it turns out yesterday we had an internal request to do something like this (basically we needed an easy way to do a vote system and tally the results).

Below is a sample of 3 questions, a single-select, a multi-select, and a text field. Currently it really only implements counting up the number of answers to a specific question. I'm not sure how the Average or Cumulative would work. Seems like that would _only_ work with an `Integer` field type. If that is what you were thinking, I could probably add some logic that if the field type was Integer, it would add labels above the chart to show the Average and Cumulative numbers.

![Screenshot_2020-05-19 Charts Rock RMS](https://user-images.githubusercontent.com/1119863/82352908-8652f200-99b3-11ea-9aa3-f1a497d6d72e.png)

**Comment by rutledgek** [comment]
Sounds good. I guess I was also thinking of range slider could show a count of the various scores and an average.
